### ISSUE TITLE
Cross compile for windows

### ISSUE THREAD

**Issue by BigNerd95** [dh1tw/goHamlib#8]
Is it possible to cross compile goHamlib for windows, on linux?

**Comment by dh1tw** [comment]
Hi @BigNerd95,
cross compiling with cgo is a bit tricky, but it's certainly possible. Usually I'm using docker for these tasks. For another project of mine ([remoteAudio](https://github.com/dh1tw/remoteAudio)) I created [remoteAudio-xcompile](https://github.com/dh1tw/remoteAudio-xcompile), basically a set of Dockerfiles with the cross-compilers and dependencies for a bunch of OS and architectures (incl Windows). I think it's pretty easy to adapt them to goHamlib.

**Comment by BigNerd95** [comment]
Thank you! I'll try to do that!
I also found your article describing all this https://dh1tw.de/2019/12/cross-compiling-golang-cgo-projects/
One more question: why did you compile the windows version dynamically and not statically as for linux?

Congrats for all your projects!

**Comment by dh1tw** [comment]
I think this is related to using [upx](https://upx.github.io) for compressing the binaries. After compressing the binary with upx, `file remoteAudio` will falsely indicate that the binary is statically linked.
